import assert from "node:assert/strict";
import { chmod, mkdir, mkdtemp, readFile, stat } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { acceptClaudeModelOperation, captureClaudeModelOperationStop, cleanupClaudeModelOperation, recoverClaudeModelOperation } from "../src/claude-model-operation.mjs";
import { ObserverError } from "../src/observer-error.mjs";

const targetId = `p_${"a".repeat(64)}`; const operationId = `sha256:${"b".repeat(64)}`; const generationId = `sha256:${"c".repeat(64)}`; const expected = { job_id: "job-1", session_id: "session-1", cwd: "/observer", name: "observer-job" };
async function setup() { const root = await mkdtemp(join(tmpdir(), "claude-operation-")); await chmod(root, 0o700); await mkdir(join(root, "watches", targetId), { recursive: true, mode: 0o700 }); return root; }
const agents = () => JSON.stringify([{ id: "job-1", sessionId: "session-1", cwd: "/observer", name: "observer-job", kind: "background", state: "working", account: "must-not-save" }]);
const payload = (patch = {}) => ({ hook_event_name: "Stop", session_id: "session-1", cwd: "/observer", stop_hook_active: false, last_assistant_message: '{"schema":"observer.ai_output.v1","outcome":"no_advisory"}', ...patch });
const advisory = JSON.stringify({ schema: "observer.ai_output.v1", outcome: "advisory", proposal: { title: "t", body: "b", suggested_action: "a", dedupe_key: "d", evidence_refs: ["e"], severity: "warning", category: "scope_drift" } });
const expectCode = (code) => (error) => error instanceof ObserverError && error.code === code;

test("agents exact相関でacceptedを0600 journalへ保存しSupervisor callback shapeとreceiptを不変にする", async () => { const root = await setup(); const first = await acceptClaudeModelOperation({ stateRoot: root, targetId, operationId, generationId, expected, agentsStdout: agents() }); const second = await acceptClaudeModelOperation({ stateRoot: root, targetId, operationId, generationId, expected, agentsStdout: agents() }); assert.deepEqual(Object.keys(first).sort(), ["outcome", "provider_operation_receipt_digest", "schema"]); assert.equal(first.provider_operation_receipt_digest, second.provider_operation_receipt_digest); const path = join(root, "watches", targetId, "provider-operations", "claude-model-operation.json"); assert.equal((await stat(path)).mode & 0o777, 0o600); assert.equal((await readFile(path, "utf8")).includes("must-not-save"), false); });
test("Stop captureはactive true/false双方をstrict canonical化し、同一replayだけ冪等にする", async () => { const root = await setup(); await acceptClaudeModelOperation({ stateRoot: root, targetId, operationId, generationId, expected, agentsStdout: agents() }); assert.equal((await captureClaudeModelOperationStop({ stateRoot: root, targetId, operationId, payload: payload() })).outcome, "completed"); assert.equal((await captureClaudeModelOperationStop({ stateRoot: root, targetId, operationId, payload: payload({ stop_hook_active: true }) })).outcome, "completed"); await assert.rejects(captureClaudeModelOperationStop({ stateRoot: root, targetId, operationId, payload: payload({ last_assistant_message: advisory }) }), expectCode("E_CLAUDE_OPERATION_OUTPUT_CONFLICT")); });
test("StopFailure/session mismatch/invalid outputはcompletedにせずgeneric status別にaccepted/pendingを返す", async () => { const root = await setup(); const accepted = await acceptClaudeModelOperation({ stateRoot: root, targetId, operationId, generationId, expected, agentsStdout: agents() }); assert.deepEqual(await recoverClaudeModelOperation({ stateRoot: root, targetId, operationId, operationStatus: "dispatching" }), accepted); assert.deepEqual(await recoverClaudeModelOperation({ stateRoot: root, targetId, operationId, operationStatus: "accepted" }), { schema: "observer.model_operation_callback.v1", outcome: "pending" }); assert.equal((await captureClaudeModelOperationStop({ stateRoot: root, targetId, operationId, payload: payload({ hook_event_name: "StopFailure" }) })).outcome, "unknown"); assert.equal((await captureClaudeModelOperationStop({ stateRoot: root, targetId, operationId, payload: payload({ session_id: "other" }) })).outcome, "unknown"); assert.equal((await captureClaudeModelOperationStop({ stateRoot: root, targetId, operationId, payload: payload({ last_assistant_message: "not-json" }) })).outcome, "unknown"); });
test("provider journal欠損は再送せずprovider_operation_missingを返す", async () => { const root = await setup(); assert.deepEqual(await recoverClaudeModelOperation({ stateRoot: root, targetId, operationId, operationStatus: "dispatching" }), { schema: "observer.model_operation_callback.v1", outcome: "unknown", reason: "provider_operation_missing" }); });
test("malformed/terminal/duplicate agentsはunknown、completed recoveryはcanonical raw_outputを返す", async () => { const root = await setup(); await assert.rejects(acceptClaudeModelOperation({ stateRoot: root, targetId, operationId, generationId, expected, agentsStdout: "{}" }), expectCode("E_CLAUDE_OPERATION_AGENTS_INVALID")); assert.equal((await acceptClaudeModelOperation({ stateRoot: root, targetId, operationId, generationId, expected, agentsStdout: JSON.stringify([{ ...JSON.parse(agents())[0], state: "done" }]) })).outcome, "unknown"); assert.equal((await acceptClaudeModelOperation({ stateRoot: root, targetId, operationId, generationId, expected, agentsStdout: JSON.stringify([JSON.parse(agents())[0], JSON.parse(agents())[0]]) })).outcome, "unknown"); await acceptClaudeModelOperation({ stateRoot: root, targetId, operationId, generationId, expected, agentsStdout: agents() }); await captureClaudeModelOperationStop({ stateRoot: root, targetId, operationId, payload: payload() }); const recovered = await recoverClaudeModelOperation({ stateRoot: root, targetId, operationId, operationStatus: "accepted" }); assert.deepEqual(Object.keys(recovered).sort(), ["outcome", "provider_operation_receipt_digest", "raw_output", "schema"]); assert.equal(recovered.raw_output, payload().last_assistant_message); });
test("cleanupはgeneric completed一致後だけ可能で、欠損journalも同じreceipt/output証拠を要求する", async () => { const root = await setup(); const accepted = await acceptClaudeModelOperation({ stateRoot: root, targetId, operationId, generationId, expected, agentsStdout: agents() }); await captureClaudeModelOperationStop({ stateRoot: root, targetId, operationId, payload: payload() }); const journal = JSON.parse(await readFile(join(root, "watches", targetId, "provider-operations", "claude-model-operation.json"), "utf8")); const evidence = { provider_operation_receipt_digest: accepted.provider_operation_receipt_digest, completed_output_digest: journal.canonical_output_digest }; const generic = { status: "completed", provider: "claude", operation_id: operationId, ...evidence }; await assert.rejects(cleanupClaudeModelOperation({ stateRoot: root, targetId, operationId }, { readModelOperation: async () => null }), expectCode("E_CLAUDE_OPERATION_CLEANUP_FORBIDDEN")); assert.deepEqual(await cleanupClaudeModelOperation({ stateRoot: root, targetId, operationId }, { readModelOperation: async () => generic }), { schema: "observer.model_operation_cleanup.v1", outcome: "cleaned" }); await assert.rejects(cleanupClaudeModelOperation({ stateRoot: root, targetId, operationId }, { readModelOperation: async () => generic }), expectCode("E_CLAUDE_OPERATION_CLEANUP_FORBIDDEN")); assert.deepEqual(await cleanupClaudeModelOperation({ stateRoot: root, targetId, operationId, cleanupEvidence: evidence }, { readModelOperation: async () => generic }), { schema: "observer.model_operation_cleanup.v1", outcome: "cleaned" }); });
